# Generated by Django 3.0.7 on 2020-08-30 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listotvet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otvet', models.CharField(default='0', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('question_answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Listscore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('otvet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Listotvet')),
            ],
        ),
        migrations.AddField(
            model_name='listotvet',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
